### PR TITLE
Add Kubernetes and DevOps Video Resources

### PR DESCRIPTION
**Pull request by hemmatt**

### CODE REVIEW

**Review by SepehrRasouli — CHANGES_REQUESTED** [review]
Hi there, 
Thank you for your kind contribution. Unfortunately the table of content and some of the contents are not RTL, Could you fix them ?
Try removing the spaces between titles in the table of content and adding spaces between titles and contents.
Wish you the best.

**Comment by hemmatt** [comment]
> Hi there, Thank you for your kind contribution. Unfortunately the table of content and some of the contents are not RTL, Could you fix them ? Try removing the spaces between titles in the table of content and adding spaces between titles and contents. Wish you the best.

Do you mean in entire repo ?
In any case, i can do that.

**Comment by SepehrRasouli** [comment]
Yes i mean the entire repository. Thank you for your contribution.

**Comment by BobbyBabazadeh** [comment]
Hi, Why did you close the pull request @hemmatt ?
Would you mind to do some changes or just giving up on making a change?

**Comment by hemmatt** [comment]
> Hi, Why did you close the pull request @hemmatt ? Would you mind to do some changes or just giving up on making a change?

Hi, I was making some changes according to the @SepehrRasouli  mentions. i thought  it's better to close this PR and make a pull request with all of  that mentions.

**Comment by BobbyBabazadeh** [comment]
Great, Thanks, We are looking forward to your next pull request dear @hemmatt

**Pull request closed without merging**
